name: film-owl

services:
    service1:
        build: ./film-owl-backend/service1
        ports:
            - "5000:8000"
        volumes:
            - ./film-owl-backend/service1:/app
        environment:
            - FLASK_ENV=development
        # based off of https://docs.docker.com/reference/compose-file/develop/
        develop:
            watch:
                - path: ./film-owl-backend/service1
                  action: rebuild

    service2:
        build: ./film-owl-backend/service2
        ports:
            - "5001:8000"
        volumes:
            - ./film-owl-backend/service2:/app
        environment:
            - FLASK_ENV=development
        develop:
            watch:
                - path: ./film-owl-backend/service2
                  action: rebuild

    ui:
        build: ./film-owl-ui
        ports:
            - "3000:3000"
        develop:
            watch:
                - path: ./film-owl-ui
                  action: sync
                  target: /app

    db:
        image: postgres:13
        ports:
            - "5411:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: film-owl
        volumes:
            - ./db:/docker-entrypoint-initdb.d/

    adminer:
        image: adminer
        ports:
            - "8080:8080"
